### ISSUE TITLE
remote ssh dev: extension error UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by derekwallace** [redhat-developer/yaml-language-server#182]
HI,
Windows 10
VSCode 1.37.1
Remove SSH to a linux 

I have YAML extension loaded locally. Beside the extension it says load on remote server
![image](https://user-images.githubusercontent.com/5574230/64644410-85bc9180-d40a-11e9-82e6-9854fcdafdb5.png)

If i load on remote servers, it installs. but yaml files then trigger errors in Output window

[Error - 9:31:34 PM] (node:30174) UnhandledPromiseRejectionWarning: #<Object>
[Error - 9:31:34 PM] (node:30174) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 9:31:34 PM] (node:30174) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 9:31:34 PM] (node:30174) UnhandledPromiseRejectionWarning: #<Object>
[Error - 9:31:34 PM] (node:30174) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by JPinkney** [comment]
Probably related to https://github.com/redhat-developer/vscode-yaml/issues/127

**Comment by JPinkney** [comment]
Hello, this should be fixed in the latest release 0.5.3!

**Comment by ahmed-masud** [comment]
It's not fixed ...  
Error: ENOENT: no such file or directory, open '/Users/masud/Library/Application Support/Code - Insiders/User/settings.json'

(node:20003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

<img width="2123" alt="Screen Shot 2019-10-10 at 8 17 59 PM" src="https://user-images.githubusercontent.com/1837276/66615539-1ff32f00-eb9b-11e9-8158-d598fcb7df6b.png">

What's happening is that the extension "thinks" that it's in an OSX environment, because that's what I am using for remote editing.  However my remote is a linux box, and the extension is installed on the remote. However the extension is looking for settings.json as if it were on OSX and is not able to find it. Thus the ENOENT.  Then it's also not catching the promise.

I'll try to see if I can submit a fix next weekend, however if you know where the issue is then it'd be great to get a patch

**Comment by JPinkney** [comment]
Is this just happening in the cloud code YAML Support output channel? Does this occur in the VSCode-YAML output channel? I believe the cloud code extension forked this code and if that is the case they probably haven't ported the fix to their code
