### ISSUE TITLE
yaml.schemas priority is lower than schemaStore

### ISSUE THREAD

**Issue by alex-enchi** [redhat-developer/yaml-language-server#250]
I was trying to use vscode-yaml for ansible configuration recently, specifically this one schema `http://json.schemastore.org/ansible-stable-2.9` but there's a small bug where yum supports only string as input.

Afterwards I've added configuration to use custom schema
```
"settings": {
		"yaml.schemas": {
			"./ansible-stable-2.9-local.json": "*",
		}
	}
```
I guess that file loads properly, because on hover it gets proper description for properties and autocomplete, but validation not.

After I've added `"yaml.schemaStore.enable": false,` to settings I am getting both hover information and rules from local file.

**Comment by apupier** [comment]
@JPinkney do you have pointers to improve that?

I was looking to https://github.com/redhat-developer/yaml-language-server/blob/3cdc18b4329eea9facf336bb21c3fda72d139a2a/src/languageservice/services/yamlSchemaService.ts#L217 but I don't see any other reference to `this.filePatternAssociations` so don't understand how it is built.
We would need having 2 lists? one from schemastore and one from yaml.schemas?
Maybe also need to differentiate the languageSettings.schemas https://github.com/redhat-developer/yaml-language-server/blob/d65a753f566b845373037be0dd252bb6d8855ad4/src/server.ts#L162 ?

**Comment by JPinkney** [comment]
filePatternsAssociations stuff is all passed through to the JSON language service IIRC.

I think to fix this issue we need to introduce priorities for schemas like suggested. Something like https://github.com/redhat-developer/vscode-yaml/issues/151 should always be priority 1, meaning that if it is present, no matter what it will use it and nothing else.

Then I think local schemas can be priority 2, meaning any other local schemas can be matched with the file.

Then schema store schemas would be priority 3 and are only used if nothing else matches.

**Comment by idoprz** [comment]
Hi @gorkem ,
Nice to meet once again :)

I have somewhat similar problem. There is some schema in the store that matches everything with the keyword "deploy". The store also have specific match for filetype "ui5-deploy.yaml", which is the schema i want to be used.
Should the matcher have higher priority for exact match (in my case ui5-deploy.yaml)? or somehow to be able to configure it?
I also tried to override it somehow using yaml.schemas but it doesn't work.

**Comment by JPinkney** [comment]
This issue should be fixed in 0.14.0! yaml.schemas should not have a higher priority than the schemaStore. If there are still any issues please let me know.

@idoprz Can you please open a separate issue with that info when you get a chance. As of 0.14.0 all schemas coming from the same source are equally valid regardless of whether they are an exact match or matched with a glob pattern

**Comment by JefferyHus** [comment]
@JPinkney This issue is still happening.

![Screenshot 2021-03-23 at 20 38 32](https://user-images.githubusercontent.com/3521144/112207694-bd1f1780-8c17-11eb-8ee2-c7e49a61fe69.png)

![Screenshot 2021-03-23 at 20 37 33](https://user-images.githubusercontent.com/3521144/112207582-9a8cfe80-8c17-11eb-97ee-66526a05c24c.png)

**Comment by proteriax** [comment]
Still reproducible.

**Comment by sangdth** [comment]
> Still reproducible.
I can confirm I still have this issue in openapi.yaml, where my custom `"yaml.schema.openapi"` has no effect, and the schemaStore still enforce it with `3.1.0`.
<img width="863" alt="Screenshot 2021-11-30 at 12 17 58" src="https://user-images.githubusercontent.com/1083478/144042452-d0c49195-936d-4dc2-a08a-a8defefd6b47.png">
