### ISSUE TITLE
Absent --help

### ISSUE THREAD

**Issue by ulidtko** [redhat-developer/yaml-language-server#314]
Hi!

I'm trying to set this up, with [LanguageClient-NeoVim](https://github.com/autozimu/LanguageClient-neovim/wiki/yaml-language-server) — and it doesn't work — and I don't know why. Any help?

```
$ yaml-language-server --help
/usr/local/lib/node_modules/yaml-language-server/node_modules/vscode-languageserver/lib/main.js:700
        throw new Error("Connection input stream is not set. " + commandLineMessage);
        ^

Error: Connection input stream is not set. Use arguments of createConnection or set command line parameters: '--node-ipc', '--stdio' or '--socket={number}'
    at _createConnection (/usr/local/lib/node_modules/yaml-language-server/node_modules/vscode-languageserver/lib/main.js:700:15)
    at Object.createConnection (/usr/local/lib/node_modules/yaml-language-server/node_modules/vscode-languageserver/lib/main.js:647:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/yaml-language-server/out/server/src/server.js:258:42)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yaml-language-server/bin/yaml-language-server:3:1)
```

**Comment by ulidtko** [comment]
In particular, I need to know if there's a `--config` option — to be able to pass my `settings.json` — to be able to run the LSP server in isolation — as a basic troubleshooting step to diagnose whether it's the IDE plugin at fault or the LSP server itself.

**Comment by evidolob** [comment]
Hi, no we do not have any additional options for language-server others than [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node) provides. But all of them is only for specifying connection type.

As by LSP specification, LS lifetime is fully managed by IDE, so we never design yaml-language-server to work in standalone(isolated) mode. As, according to specification, initialization of LS is quite complex process, see [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize)

Just to make sure that yaml-ls works, you can run `yaml-language-server --stdio`, it will force to use stdin/stdout of process as connection, but yaml-ls will not start work until it not initialized properly.

Can you provide more info about what doesn't work? Any traces or error messages?

**Comment by ulidtko** [comment]
If I run it with `--stdio` — it outputs nothing, and apparently just hangs in a blocked state (likely, IO).

From the vim client — I get timeouts for any requests to the LSP.

How should I proceed troubleshooting this? Any debug enabling tricks?

**Comment by evidolob** [comment]
> If I run it with `--stdio` — it outputs nothing, and apparently just hangs in a blocked state (likely, IO).

Yes it waits for [initialise notification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize)

> From the vim client — I get timeouts for any requests to the LSP.
>
> How should I proceed troubleshooting this? Any debug enabling tricks?

Unfortunately, I'm not an expert on vim, the only thing that I can suggest is try to debug your vim connection to yaml-ls, and make sure that LS receive `initialize` notification and sends back `InitializeResult`, without any errors.

**Comment by ulidtko** [comment]
OK, but to see that I'd need to intercept the stdio connection somehow.

I think I can do it with a wrapper script; please hold until I get back with something.

**Comment by evidolob** [comment]
And [LanguageClient-neovim#installation](https://github.com/autozimu/LanguageClient-neovim/wiki/yaml-language-server#installation) says that latest version of yaml-language-server does not work with LanguageClient-neovim, maybe it is something to ask on LanguageClient-neovim?

**Comment by JPinkney** [comment]
I believe the neovim issue for 0.5.8 was fixed, the docs just weren't updated. It should work for anything > then 0.6.0

**Comment by ulidtko** [comment]
> And [LanguageClient-neovim#installation](https://github.com/autozimu/LanguageClient-neovim/wiki/yaml-language-server#installation) says that latest version of yaml-language-server does not work with LanguageClient-neovim, maybe it is something to ask on LanguageClient-neovim?

No, as you can see that wiki is woefully outdated, stating 0.5.8 as "the latest" yaml-ls (while I've installed 0.10.1). Maybe the original issue is still there, maybe it's not — I've no way of knowing exactly yet.

**Comment by ulidtko** [comment]
Hmmm, so it appears that nothing at all is exchanged on the pipes. So, like you say @evidolob, yaml-ls is waiting for an `initialize` message — but the vim plugin is not sending it.

I'll see what I can find to understand this better. @JPinkney do you perhaps have links to relevant issues/PRs/changes? That'd help a lot to understand the context.

Finally, I think that adding debugging facilities to LSP server can still be done without violating the spec. Comparing to [haskell-language-server][] which outputs a pretty detailed log to STDERR — I don't have to guess, ask or find from the source which state it's in, what errors it got and so on. Perhaps consider adding something similar — it'd be a big favor for editor integration writers.

[haskell-language-server]: https://github.com/haskell/haskell-language-server

**Comment by evidolob** [comment]
> Finally, I think that adding debugging facilities to LSP server can still be done without violating the spec. Comparing to [haskell-language-server](https://github.com/haskell/haskell-language-server) which outputs a pretty detailed log to STDERR — I don't have to guess, ask or find from the source which state it's in, what errors it got and so on. Perhaps consider adding something similar — it'd be a big favor for editor integration writers.

Yes, that is a good point, maybe we can add similar stuff. @JPinkney WDYT?
