### ISSUE TITLE
Rejects schemas where $ref refers to $id or $anchor

### ISSUE THREAD

**Issue by sam-mccall** [redhat-developer/yaml-language-server#823]
## Describe the bug

When processing schemas, the server seems to assume that the hash part a `$ref` is always a JSON pointer.

Therefore the following schema can't be loaded, with an error `$ref 'A' in 'file:///...' can not be resolved.`

Schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "A": { "$id": "#A", "type": "string" },
    "B": { "$ref": "#A" }
  }
}
```

Example valid doc:
```
# yaml-language-server: $schema=fail.schema.json
A: foo
B: bar
```

## Expected Behavior
Schema loads and document validates correctly.

The [draft-07 spec](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01#section-8.3.2) says:

> Schemas can be identified by any URI that has been given to them, including a JSON Pointer or their URI given directly by "$id".

and goes on to give a very similar example.

## Current Behavior
Language server shows the error: `$ref 'A' in 'file:///...' can not be resolved.`

For the 2019 JSON-schema spec, we should use  `"$anchor": "A"` instead of "$id": "#A"`. This also doesn't work.

Using a JSON-pointer link `"$ref": "/properties/A"` does work.

## Steps to Reproduce
1. Save the files above as `fail.schema.json` and `fail.yaml`
2. Open `fail.yaml` in an editor talking to yaml-language-server
3. See spurious diagnostics on the first line of content

## Environment
- [ ] Windows
- [ ] Mac
- [X] Linux
- [ ] other (please specify)

**Comment by sam-mccall** [comment]
Browsing the code [findSection()](https://github.com/redhat-developer/yaml-language-server/blob/b63cee842597e73ae692efd35cece4c7f9eb414a/src/languageservice/services/yamlSchemaService.ts#L176-L190) looks suspicious: it seems ids/anchors would have to be handled somewhere near there, rather than just assuming the hash fragment is a JSON pointer.

**Comment by gorkem** [comment]
We are using vscode-json-langaugeservice to resolve schemas. This has been fixed upstream, we probably need to adjust to this later version.

**Comment by kujon** [comment]
This is still broken in 2025 btw. Do you know what needs to happen for this to be solved? I would love to help.

**Comment by kujon** [comment]
@gorkem do you happen to know more?

**Comment by rcjsuen** [comment]
> We are using vscode-json-langaugeservice to resolve schemas. This has been fixed upstream, we probably need to adjust to this later version.

Looks like that comment is from March 2023 and the project today still uses [4.1.8](https://github.com/microsoft/vscode-json-languageservice/releases/tag/v4.1.8) (from Sept 2021) and there's now a [5.6.0](https://github.com/microsoft/vscode-json-languageservice/releases/tag/v5.6.0) from last week. 🤔

https://github.com/redhat-developer/yaml-language-server/blob/c94fa43591254f07ffd0daad437edd4099049eb3/package.json#L33

**Comment by kujon** [comment]
So the fix was rolled out in 4.2.0 (https://github.com/microsoft/vscode-json-languageservice/pull/107). This included a bit of a refactor to `JSONSchemaService`. Since [`YAMLSchemaService`](https://github.com/redhat-developer/yaml-language-server/blob/main/src/languageservice/services/yamlSchemaService.ts#L109) is subclassing an internal class, this is quite tedious to update, even to 4.2.0. Could someone summarise what are the intended changes in `YAMLSchemaService` compared to the original before I take a crack at fixing this?

**Comment by kujon** [comment]
Draft: https://github.com/redhat-developer/yaml-language-server/pull/1087. Needs more work as there are 7 failing tests
